# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Norwegian Nynorsk spellchecker"
nn = "Nynorsk stavekontroll"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Norwegian Nynorsk, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
nn = "Ein stavekontroll for norsk m책l, tufta p책 data fr책 spr책kbanken, jobba vidare med av Divvun- og Giellatekno-gruppene ved UiT Noregs arktiske universitet"

[macos]
system_pkg_id = "no.divvun.MacDivvun.nn"

[windows]
system_product_code = "{D5C8B3E2-FF5D-4F22-ABE5-55C68978DD0D}_is1"
legacy_product_codes = [
    { value = "5CA7541A-A523-4833-A03B-292368F9375B", kind = "nsis" },
    { value = "6BCE53FF-151A-4238-89D8-92AA9F0F7B0F", kind = "nsis" }
]

[package.speller]
name = "Norwegian Nynorsk"
version = "0.1.1"

[package.grammar]
name = "Norwegian Nynorsk"
version = "0.1.0"

[package.tts-text-proc]
name = "Norwegian Nynorsk"
version = "0.1.0"

[package.hyphenator]
name = "Norwegian Nynorsk"
version = "0.1.0"
